name: Windows-RDP-Direct

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Setup Direct RDP with Playit
        shell: powershell
        run: |
          # 1. Bat Remote Desktop
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0

          # 2. Dat mat khau dang nhap
          net user runneradmin "MatKhauManh123@"

          # 3. Tai Playit CLI
          Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "playit.exe"

          # 4. Khoi chay va tao tunnel TCP port 3389
          $process = Start-Process -FilePath ".\playit.exe" -PassThru

          Write-Host "`n=======================================================" -ForegroundColor Cyan
          Write-Host "DANG KHOI TAO PHIEN KET NOI..." -ForegroundColor Yellow
          Write-Host "Username   : runneradmin" -ForegroundColor Yellow
          Write-Host "Password   : MatKhauManh123@" -ForegroundColor Yellow
          Write-Host "=======================================================`n" -ForegroundColor Cyan

          # 5. Chay tiep tuc de giu ket noi
          $timeout = 21600
          Start-Sleep -Seconds $timeout
